basic/models/Continent.php
<?php
namespace app\models;
use yii\db\ActiveRecord;

class Continent extends ActiveRecord{

}

basic/controllers/ContinentController.php
<?php

namespace app\controllers;

use app\models\Continent;
use app\models\Country;
use app\models\CountrySearch;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\bootstrap5\LinkPager;

class ContinentController extends Controller
{
    public function actionIndex()
    {
        $continents=Continent::find()->asArray()->all();
        return $this->render('index',['continents'=>$continents]);
    }

    public function actionView($continent_id)
    {
        $continent = Continent::findOne($continent_id);
        $countriesDataProvider = new ActiveDataProvider([
            'query' => Country::find()->where(['continent_id' => $continent_id]),
            'pagination' => [
                'pageSize' => 20,
            ]
        ]);

       return $this->render('view', compact('continent', 'countriesDataProvider'));
    }
}

basic/controllers/CountryController.php
<?php


namespace app\controllers;

use app\models\Continent;
use app\models\CountrySearch;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\Country;

class CountryController extends Controller
{
    public function actionIndex()
    {
        $query = Country::find();

        $pagination = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $countries = $query->orderBy('name')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('index', [
            'countries' => $countries,
            'pagination' => $pagination,
        ]);
    }
    public function actionView($code)
    {
        $country = Country::findOne(['code'=>$code]);

//        $countrySearchModel = new CountrySearch();
////        $countryDataProvider = $countrySearchModel->search($this->request->queryParams);
//        $countriesDataProvider = new ActiveDataProvider([
//            'query' => Country::find()->where(['continent_id' => $continent_id]),
//            'pagination' => [
//                'pageSize' => 20,
//            ]
//        ]);

        return $this->render('view', compact('country'));
    }

}

basic/views/continent/_country.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>
<a href="<?= Url::to(['country/view', 'code' => $model->code]) ?>" class="list-group-item list-group-item-action">
    <?= Html::img('@web/images/countries/png100px/' . strtolower($model['code']) . '.png', ['alt' => $model['name']]) ?>
    <?= Html::encode($model->name) ?>
</a>

basic/views/continent/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

?>
<div class="row">
    <?php
    foreach ($continents as $continentItem):?>
        <div class="card  m-3 p-0 border-primary" style="width: 370px">
        <a href="<?= Url::to(['continent/view', 'continent_id' => $continentItem['continent_id']]); ?>"
           class="list-group-item">
                <h5 class="card-header bg-primary text-white"><?= Html::encode($continentItem['name']) ?></h5>
                <div class="card-body">
                    <?= Html::img('@web/images/continents/' . Html::encode($continentItem['code']) . '.png', ['alt' => Html::encode($continentItem['name']),'class'=>"img-thumbnail"])  ?>
                    <p class="card-text"><?= Html::encode($continentItem['description']) ?></p>
                </div>
        </a>
        </div>
    <?php endforeach; ?>
</div>

basic/views/continent/view.php
<?php
use yii\helpers\Html;
use app\controllers\ContinentController;
use yii\widgets\ListView;
use yii\bootstrap5\LinkPager;
$this->title=$continent->name;

$this->params['breadcrumbs'][]=['label'=>'Continents','url'=>['continent/index']];
$this->params['breadcrumbs'][]=['label'=>$continent['name'],'url'=>['continent/view','continent_id'=>$continent['continent_id']]];
?>
<section id="continent-view">
    <div class="container">
        <h1><?= Html::encode($this->title)?></h1>
        <p><?= Html::encode($continent->description)?></p>
        <?=ListView::widget([
                'dataProvider'=>$countriesDataProvider ,
                'itemView'=>'_country',
                'layout'=>"{items}\n{summary}\n{pager}",
                'options'=>[
                        'class'=>'list-group'
                ],
                'itemOptions'=>[
                        'tag'=>false,
                ],

        ]);?>


    </div>
</section>