basic/models/Country.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

class Country extends ActiveRecord
{
}

basic/controllers/ContinentController.php
<?php

namespace app\controllers;

use app\models\Continent;
use app\models\Country;
use app\models\CountrySearch;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\bootstrap5\LinkPager;

class ContinentController extends Controller
{
    public function actionIndex()
    {
        $continents=Continent::find()->asArray()->all();
        return $this->render('index',['continents'=>$continents]);
    }

    public function actionView($continent_id)
    {
        $continent = Continent::findOne($continent_id);
        $countriesDataProvider = new ActiveDataProvider([
            'query' => Country::find()->where(['continent_id' => $continent_id]),
            'pagination' => [
                'pageSize' => 20,
            ]
        ]);

       return $this->render('view', compact('continent', 'countriesDataProvider'));
    }
}

basic/controllers/CountryController.php
<?php


namespace app\controllers;

use app\models\Continent;
use app\models\CountrySearch;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\Country;

class CountryController extends Controller
{
    public function actionIndex()
    {
        $query = Country::find();

        $pagination = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $countries = $query->orderBy('name')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('index', [
            'countries' => $countries,
            'pagination' => $pagination,
        ]);
    }
    public function actionView($code)
    {
        $country = Country::findOne(['code'=>$code]);

//        $countrySearchModel = new CountrySearch();
////        $countryDataProvider = $countrySearchModel->search($this->request->queryParams);
//        $countriesDataProvider = new ActiveDataProvider([
//            'query' => Country::find()->where(['continent_id' => $continent_id]),
//            'pagination' => [
//                'pageSize' => 20,
//            ]
//        ]);

        return $this->render('view', compact('country'));
    }

}

basic/views/country/index.php
<?php

use yii\helpers\Html;
use yii\bootstrap5\LinkPager;
?>
    <h1>Країни</h1>
    <ul>
        <?php foreach ($countries as $country): ?>
            <li>
                <?= Html::encode("{$country->name} ({$country->code})") ?>:
                <?= $country->population ?>
            </li>
        <?php endforeach; ?>
    </ul>

<?= LinkPager::widget(['pagination' => $pagination]) ?>

basic/views/country/view.php
<?php

use yii\helpers\Html;

$this->title = $country->name;

$this->params['breadcrumbs'][] = ['label' => 'Continents', 'url' => ['continent/index']];
$this->params['breadcrumbs'][] = ['label' => 'Country', 'url' => ['continent/view', 'continent_id' => $country['continent_id']]];
$this->params['breadcrumbs'][] = $this->title;
?>
<script async
        src="https://maps.googleapis.com/maps/api/js?sensor=false&callback=initMap">
</script>
<script>
    function initMap() {

        let lat=JSON.parse("<?php echo $country['coords'];?>")[0]
        let lng=JSON.parse("<?php echo $country['coords'];?>")[1]
        console.log(lng)
        let myLatLng = {lat: lat, lng: lng};
        let map = new google.maps.Map(document.getElementById('map'), {
            zoom: 6,
            center: myLatLng
        });
        let marker = new google.maps.Marker({
            position: myLatLng,
            map: map,
            title: 'My point'
        });
    }
</script>
<body onload="initMap()">
<h1><?= Html::encode($this->title) ?></h1>
<div class="row">
<table class="table table-striped" style="margin-right: 10px; width: 48%;">
    <tr>
        <th>Official Name</th>
        <td><?= Html::encode($country->name) ?></td>
    </tr>
    <tr>
        <th>Image</th>
        <td> <?= Html::img('@web/images/countries/png250px/' . strtolower(Html::encode($country->code)) . '.png', ['alt' => Html::encode($country->name), 'class' => "img-thumbnail"]) ?>
        </td>
    </tr>
    <tr>
        <th>Capital</th>
        <td><?= Html::encode($country->capital) ?></td>
    </tr>
    <tr>
        <th>Area</th>
        <td><?= Html::encode($country->area) ?></td>
    </tr>
    <tr>
        <th>Currency</th>
        <td><?= Html::encode($country->currency) ?></td>
    </tr>
</table>
<div id="map" style="width: 48%; height: 500px;"></div>
</div>
</body>